spring:
  datasource:
    #MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wetrash?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: create-drop #? ??? ???? ?? ???? ?? ???
    properties:
      hibernate:  #Hibernate? ??? ?? ?????? ???? crud ????
        show_sql: true #jpa ??? ?? ??
        format_sql: true #Hibernate? ??? SQL ??? ????? ??? ???? ??


